version: '3'
services:
  backupper:
    restart: always
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./repos:/repos-backup
volumes:
  repos-backup:
